name: "GHA telemetry info"
description: Returns identifier metadata that is useful in OpenTelemetry
inputs:
  traceparent:
    description: Combination of the trace id and span id in a particular format

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm install @opentelemetry/api
      shell: bash
    - uses: actions/github-script@v7
      id: get-job-info
      with:
        retries: 3
        script: |
          const opentelemetry = require('@opentelemetry/api');

          var ctx = opentelemetry.propagation.extract(opentelemetry.context.active(), {"traceparent": "${{ inputs.traceparent }}", "tracestate": ""});

          console.log("TRACEPARENT")
          console.log("${{ inputs.traceparent }}")
          console.log("OTel context after extracting")
          console.log(ctx)
