on:
  pull_request:
  push:
  workflow_dispatch:

env:
  traceparent: "00-397d8af9dc0e32f3c7a672114a3303b53dd1d66a7c9cd41bca9d83e3e7eeeb7f-ab995a5c9094497a-01"

jobs:
  reusable_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - uses: "./.github/actions/context-test"
        with:
            traceparent: "${{ env.traceparent }}"
  local_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm install @opentelemetry/api
      shell: bash
    - uses: actions/github-script@v7
      id: get-job-info
      with:
        retries: 3
        script: |
          const opentelemetry = require('@opentelemetry/api');

          var ctx = opentelemetry.propagation.extract(opentelemetry.context.active(), {"traceparent": "${{ env.traceparent }}", "tracestate": ""});

          console.log("TRACEPARENT")
          console.log("${{ env.traceparent }}")
          console.log("OTel context after extracting")
          console.log(ctx)
